### ISSUE TITLE
 Can't get codec for Shift-JIS, falling back to System

### ISSUE THREAD

**Issue by RaohPresident** [eliasstein/Old-SystemNNN-extractor#1]
Hi, 
I am curently trying to extract the dialogue within the 082.spt file from the english translation of Gore Screaming Show, from which I want to do an french translation. 
After running the program I get the following line :
2088 strings @3DF68
1664 resources @66CD8
Warning: Can't get codec for Shift-JIS, falling back to System
198 strings @9F80
393 resources @CAEC
Warning: Can't get codec for Shift-JIS, falling back to System

Would you know where it could come from and if it is possible to fix it?
Many thanks
Raoh

**Comment by RaohPresident** [comment]
[082.zip](https://github.com/eliasstein/Old-SystemNNN-extractor/files/11823948/082.zip)
there is the file I get from the game directory

**Comment by Cosetto** [comment]
Nope, it was because of SjisTunnelEncode by vntextpatch as you see, the characters were presented by the sjis-bytes(in hex), ddraw.dll and ext_sjis.bin helped displaying those characters. So you can only cope with the txt file extracted by this tool.
[082.txt](https://github.com/eliasstein/Old-SystemNNN-extractor/files/11827836/082.txt)

**Comment by RaohPresident** [comment]
thanks for your help, 
I got the same result so I only translate the decode text but I was not able to change it back to spt.
Do you know if there is a way to fix that?

**Comment by eliasstein** [comment]
Hi, this tool only works with the old version of Gore Screaming show. I tested with the new version of the game, and it isn't working with all the files. it only works with some files, for example the "Akane" file doesn't work, you can extract the file but it isn't possible to insert that back. i recommend you to use this one: https://github.com/arcusmaximus/VNTranslationTools

**Comment by Cosetto** [comment]
> thanks for your help, I got the same result so I only translate the decode text but I was not able to change it back to spt. Do you know if there is a way to fix that?

You didn't understand what I told you in other issue, did you? I told you to download the Japanese version and get the 082.spt from there (the Japanese  script). Place it in vntextpatch and extract like other English's scripts. And use this tool ONLY to extract the English 082.spt, after that you can make use of the extracted 082.txt from this to translate the Japanese 082.spt from vntextpatch, or paste the English's script.

**Comment by RaohPresident** [comment]
My bad, I though you where talking about using the tool to extract the txt from the English version directly.
I will try that

Many thanks for the support there
